project:
  type: website

website:
  title: Drought in Arizona
  navbar:
    background: "navajowhite"  # Replace with your desired background color
    foreground: "black"
    right:
      - icon: github
        href: https://github.com/INFO526-DataViz/project-01
    left:
      
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd
      - text: ShinyApp
        href: https://swethasiripurapu.shinyapps.io/ShinyApp/
    

format:
  html:
    theme: Sketchy
    toc: true

execute:
  freeze: auto
